artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://raw.githubusercontent.com/Giridharan79/HOUSE_PRICE_PREDICTION/refs/heads/main/final_dataset.csv
  local_data_file: artifacts/data_ingestion/data.csv
  unzip_dir: artifacts/data_ingestion

data_transform:
  root_dir: artifacts/data_transform
  local_data_file: artifacts/data_ingestion/data.csv
  train_path: artifacts/data_transform/train.csv
  test_path: artifacts/data_transform/test.csv

data_cleaning:
  root_dir: artifacts/data_clean
  train_path: artifacts/data_transform/train.csv
  test_path: artifacts/data_transform/test.csv
  cleaned_train_path: artifacts/data_clean/train.csv
  cleaned_test_path: artifacts/data_clean/test.csv

model_training:
  root_dir: artifacts/model_train
  cleaned_train_path: artifacts/data_clean/train.csv
  cleaned_test_path: artifacts/data_clean/test.csv
  model: artifacts/model_train/model.pkl

model_validation:
  root_dir: artifacts/model_validation
  cleaned_test_path: artifacts/data_clean/test.csv
  model: artifacts/model_train/model.pkl
  ResidualDistribution: artifacts/model_validation/ResidualDistribution.png
  ResidualsVSPredictions: artifacts/model_validation/ResidualsVSPredictions.png
  scores: artifacts/model_validation/scores.csv
